# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: Chinese website title...
  params:
    description: Site description in Chinese...
  menu:
    main:
  - name: Research
    url: research
    weight: 10
  - name: Publications
    url: publication
    weight: 20
  - name: Talks
    url: talk
    weight: 30
  - name: People
    url: people
    weight: 40
  - name: Teaching
    url: teaching
    weight: 50
  - name: News
    url: new
    weight: 60
  - name: Link
    url: link
    weight: 70    
  - name: Contact
    url: contact
    weight: 80
